#!/usr/bin/env node

const shopifyAPI = require('shopify-node-api')
const Moment = require('moment-timezone')
const fs = require('fs')

let commit = fs.readFileSync('./commit.txt', "utf8")
commit = commit.substring(0,20)

const Shopify = new shopifyAPI({
  shop: process.env['STORE'].replace('.myshopify.com',''), // MYSHOP.myshopify.com
  shopify_api_key: process.env['SHOPIFY_API_KEY'], // Your API key
  access_token: process.env['SHOPIFY_PASSWORD'] // Your API password
});

const timestr = Moment().tz('America/New_York').format("D.M.YY, h:mm A")

const data = {
  "theme": {
    "id": process.env.THEME_ID,
    "name": `${process.env.THEME_NAME} (${commit}.. @ ${timestr})`
  }
}

console.dir(`${process.env.THEME_NAME} (${commit}.. @ ${timestr})`)

Shopify.put(`/admin/themes/${process.env.THEME_ID}.json`, data, function(err, data, headers){
  console.log(data);
});
